{% set name = "zeroconf" %}
{% set version = "0.54.0" %}
{% set sha256 = "635f764abc8ebf2c28529d60f75c27ca777fbcebf3c9cd611339cae0e4859312" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.11
    - pip
  run:
    - python >=3.11
    - async-timeout >3.0.0
    - ifaddr >=0.1.7

test:
  imports:
    - zeroconf

about:
  home: https://github.com/jstasiak/python-zeroconf
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING
  summary: A pure python implementation of multicast DNS service discovery

extra:
  recipe-maintainers:
    - abloemert
    - niecore
