{% set version = "0.151.3" %}

package:
  name: zeroconf
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/z/zeroconf/zeroconf-{{ version }}.tar.gz
  sha256: ce6c548e665759b6150cef4db9ab9d7bdd89857e90c513abd6b7340bdd7dbd6a

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python
    - setuptools >=65.4.1
    - wheel
    - cython
    - poetry-core >=1.5.2
    - pip
  run:
    - python
    - async-timeout >=3.0.0
    - ifaddr >=0.1.7

test:
  imports:
    - zeroconf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python-zeroconf/python-zeroconf
  summary: A pure python implementation of multicast DNS service discovery
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING

extra:
  recipe-maintainers:
    - jjerphan
    - abloemert
    - niecore
    - pavelzw
