{% set name = "zeroconf" %}
{% set version = "0.119.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zeroconf-{{ version }}.tar.gz
  sha256: dbe3548ac0a68ab88241f6ac03bc6b7c19c23160bd78ed4c94ae4d92196be230

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python <4.0
    - setuptools >=65.4.1
    - wheel
    - cython
    - poetry-core >=1.5.2
    - pip
  run:
    - python >=3.7.0,<4.0.0
    - async-timeout >=3.0.0
    - ifaddr >=0.1.7

test:
  imports:
    - zeroconf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python-zeroconf/python-zeroconf
  summary: A pure python implementation of multicast DNS service discovery
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING

extra:
  recipe-maintainers:
    - jjerphan
    - abloemert
    - niecore
