{% set name = "zeroconf" %}
{% set version = "0.36.9" %}
{% set sha256 = "023ebc58b765537edcb0395367b732e5271e2659760b1d5c6119aaacaeb7b390" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - ifaddr >=0.1.7

test:
  imports:
    - zeroconf

about:
  home: https://github.com/jstasiak/python-zeroconf
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING
  summary: A pure python implementation of multicast DNS service discovery

extra:
  recipe-maintainers:
    - abloemert
    - niecore
